[theme]
primaryColor = "#4bfffc"              
backgroundColor = "#071018"             
secondaryBackgroundColor = "#03045E"    
textColor = "#ffffff"                   
font = "sans serif"


         